#+TITLE: Oefeningen MongoDB - query MongoDB
#+AUTHOR: Robin Wils
#+INCLUDE: "../org-options.org"
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../solarized-dark.min.css"/>
-----
[[file:../index.org][Home]] > [[file:mongodb.org][MongoDB]] > Query oefeningen \\
[[https://pxl-college-projects.gitlab.io/big-data-exercises-pxl.gitlab.io/mongodb/1-Query_Oefeningen.org][View org source]] \\

#+TOC: headlines

** PROJECTIE
*Bestudeer eerst de collectie movieDetails in de database video.*
*** Opgave 1
Schrijf een query die enkel de titel en de datum dat de film werd uitgebracht 
(released) toont. \\
Opmerking: de _id wordt niet getoond.

#+BEGIN_SRC mongo :db video
db.movieDetails.find({}, {_id:0 , title:1, year:1})
#+END_SRC

*** Opgave 2
Schrijf een query die enkel de titel, de landen waar de film werd gemaakt en 
de director toont. \\
Is het mogelijk om de director te tonen vlak na de titel? \\
/Nee, NoSQL heeft geen vaste structuur/

#+BEGIN_SRC mongo :db video
db.movieDetails.find({}, {title:1, director:1, countries:1})
#+END_SRC

** SORT-LIMIT-SKIP-COUNT
*** Opgave 3
Schrijf een query die de titel en de genres toont, 
alfabetisch gesorteerd volgens genre. \\
Wat valt er op bij de eerste 82 films? \\
/De eerste films in deze lijst hebben geen genre./

#+BEGIN_SRC mongo :db video
db.movieDetails.find({}, {title:1, genres:1}).sort({genres:1})
#+END_SRC

*** Opgave 4
Dezelfde opgave als 3, 
maar sla de eerste 82 films over en toon vervolgens 15 films. \\ 
Welke film staat eerst?
/Alien: Resurrection/

#+BEGIN_SRC mongo :db video
db.movieDetails.find({}, {title:1, genres:1}).skip(82).limit(15)
#+END_SRC

*** Opgave 5
Hoeveel films worden in detail besproken? (Hoeveel films zitten er in 
dit document)

#+BEGIN_SRC mongo :db video
db.movieDetails.find().count()
#+END_SRC

/Er worden 2295 films in detail besproken./

*** Opgave 6
Welke film staat op de 101ste plaats? Geef hiervan enkel de titel en 
de acteurs weer.

#+BEGIN_SRC mongo :db video
db.movieDetails.find({}, {_id:0, title:1, actors:1}).skip(100).limit(1)
#+END_SRC

*** Opgave 7
Geef de titel van de 100ste oudste film. \\
/J.P. Love in Berlin/

#+BEGIN_SRC mongo :db video
db.movieDetails.find({}, {_id:0, title:1}).sort({released:1}).skip(99).limit(1)
#+END_SRC
** SELECTIE
Ga naar de collectie movies.
*** Opgave 8
Hoeveel films zijn van het jaar 1982? \\
/22/
#+BEGIN_SRC mongo :db video
db.movies.find({year:1982}).count()
#+END_SRC

*** Opgave 9
Geef enkel de titel en het jaartal van de films van het jaar 1982.\\
Ga naar de collectie movieDetails.

#+BEGIN_SRC mongo :db video
db.movies.find({year:1982}, {_id:0, title:1, year:1})
#+END_SRC

*** Opgave 10
Geef enkel de titel weer van de films waar Stanley Kubrick director van is.

#+BEGIN_SRC mongo :db video
db.movies.find({director:"Stanley Kubrick"}, {_id:0, title:1})
#+END_SRC
*** Opgave 11
Bij hoeveel films staat er UNRATED bij het veld rated? \\
/32/
#+BEGIN_SRC mongo :db video
db.movieDetails.find({rated:"UNRATED"}).count()
#+END_SRC
*** Opgave 12
Hoeveel films zijn er waarbij de acteur Jeff Bennett meespeelt? \\
/1/
#+BEGIN_SRC mongo :db video
db.movieDetails.find({actors:'Jeff Bennett'}).count()
#+END_SRC
*** Opgave 13
Van welke films is George Lucas de director? Geef de films alfabetisch op 
titel weer.
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {director:'George Lucas'},
  {_id:0, title:1}
).sort({title:1})
#+END_SRC
*** Opgave 14
Hoeveel films duren langer dan 2 uur? \\
/262/

*Ik ben hier niet 100% zeker van sinds we de eenheid van het field "runtime" 
niet kennen. Ik vermoed dat het in minuten staat.*
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {runtime: {$gt: 120}}
).count()
#+END_SRC
*** Opgave 15 
Geef enkel de titel weer van de films waarbij acteurs met voornaam Gary in
meespelen. Geef de films alfabetisch gesorteerd weer.
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {actors: {$in: [/^Gary/]}},
  {_id:0, title:1}
).sort({title:1})
#+END_SRC
*** Opgave 16
Hoeveel films zijn van het jaar 2000 of 2010? \\
/160/
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {year: {$in: [2000,2010]}}
).count()
#+END_SRC
*** Opgave 17
Geef enkel de titel en het jaartal weer van de films van de jaren gelegen 
tussen 2014 en 2017 (inclusief), 
gesorteerd volgens ouderdom. \\
Welke film staat eerst?
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {$and:[
    {year: {$gt: 2013}},
    {year: {$lt:2018}}
  ]}
).sort({year: -1}).pretty()
#+END_SRC
*** Opgave 18
Hoeveel films zijn er van Star wars? \\
/6/
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {title: /Star wars/i}
).count()
#+END_SRC
*** Opgave 19
Welke films zijn zowel in UK als USA uitgebracht en zijn ofwel van het jaar 
2004 ofwel van 2012? \\
Toon enkel titel, jaar en countries in aflopende volgorde van het jaar en 
daarin oplopende volgorde van de titel. \\
/De lijst van films lijkt me wat lang om op te sommen./
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {$and:[
    {countries: {$in: ["USA","UK"]}},
    {year: {$in: [2004,2012]}}
  ]},
  {_id:0, title:1, year:1, countries:1}
).sort({year:1, title:1})
#+END_SRC
*** Opgave 20
Toon alle films die het woord west in de titel hebben en zijn uitgebracht in 
New Zealand en alle films waarin Bruce Willis meespeelt. \\
/De acteur Bruce Willes speelt in geen enkele film met een titel waarin "west" 
voorkomt en die in New Zealand werd uitgebracht./ 
/Daardoor hebben we geen resultaten./
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {$and:[
    {title: /west/i},
    {countries: {$in: ["New Zealand"]}},
    {actors: {$in: ["Bruce Willis"]}}
  ]},
  {_id:0, title:1}
)
#+END_SRC
*** Opgave 21
Toon alle films die niet zijn uitgebracht in USA of UK maar wel in België of 
Frankrijk. Toon enkel het id, de titel, de producer, de landen van uitgifte en 
de acteurs van de 51ste film die aan de voorwaarden voldoet.
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {$and:[
    {countries: {$nin: ["USA","UK"]}},
    {countries: {$in: ["Belgium","France"]}}
  ]},
  {_id:1, title:1, producer:1, countries:1, acteurs:1}
).skip(50).limit(1).pretty()
#+END_SRC
*** Opgave 22
Zie opgave 21 maar pas de find aan om zowel de films die in België als in 
Frankrijk zijn uitgebracht te tonen. En toon ze allemaal.
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {$and:[
    {countries: {$in: ["USA","UK"]}},
    {countries: {$in: ["Belgium","France"]}}
  ]},
  {_id:1, title:1, producer:1, countries:1, acteurs:1}
).pretty()
#+END_SRC
*** Opgave 27
Hoeveel films hebben als eerste locatie niet USA? \\
/1398 films./
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {"countries.0": {$ne: "USA"}}
).count()
#+END_SRC
*** Opgave 28
Geef de titel weer van de films waarvoor meer dan 500.000 stemmen werden 
uitgebracht en die een rating hebben van 8,5 of meer. Geef naast de rating 
ook het aantal stemmen weer.
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {$and:[
    {"imdb.rating": {$gt: 8.5}},
    {"imdb.votes": {$gt: 500000}}
  ]},
  {_id:0, title:1, "imdb.rating":1, "imdb.votes":1}
)
#+END_SRC
*** Opgave 29
Hoeveel films hebben een rating van meer dan 8,5 of hebben meer dan 
500.000 uitgebrachte stemmen? \\
/60 films./
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {$or:[
    {"imdb.rating": {$gt: 8.5}},
    {"imdb.votes": {$gt: 500000}}
  ]}
).count()
#+END_SRC
*** Opgave 30
Geef de titel weer van de films waarvoor meer dan 500.000 stemmen werden 
uitgebracht en die een rating hebben van 8,5 of meer, 
of films die op de tomato meter 90 of meer hebben. 
Geef naast de rating ook het aantal stemmen en de tomato meter weer.
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {$or:[
    {$and:[
      {"imdb.rating": {$gt: 8.5}},
      {"imdb.votes": {$gt: 500000}}
    ]},
    {"tomato.meter": {$gt: 90}}
  ]},
  {_id:0, title:1, "imdb.rating":1, "imdb.votes":1, "tomato.meter": 1}
).pretty()
#+END_SRC
*** Opgave 31
Idem opgave 30 maar sorteer volgens aantal stemmen(oplopend) en 
bij eenzelfde aantal stemmen volgens tomatometer(aflopend). 
Toon enkel de 10de tot en met 19de film.
#+BEGIN_SRC mongo :db video
db.movieDetails.find(
  {$or:[
    {$and:[
      {"imdb.rating": {$gt: 8.5}},
      {"imdb.votes": {$gt: 500000}}
    ]},
    {"tomato.meter": {$gt: 90}}
  ]},
  {_id:0, title:1, "imdb.rating":1, "imdb.votes":1, "tomato.meter": 1}
).skip(9).limit(9).sort(
  {"imdb.votes":1, "tomato.meter": -1}
).pretty()
#+END_SRC
[[file:../index.org][Home]] > [[file:mongodb.org][MongoDB]] > Query oefeningen
