// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingListApp.Data;

namespace ShoppingListApp.Data.Migrations
{
    [DbContext(typeof(ShoppingListContext))]
    partial class ShoppingListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShoppingListApp.Domain.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aldi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lidl"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Delhaize"
                        });
                });

            modelBuilder.Entity("ShoppingListApp.Domain.ShoppingList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShoppingList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Week 1"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Week 2"
                        });
                });

            modelBuilder.Entity("ShoppingListApp.Domain.ShoppingListItem", b =>
                {
                    b.Property<int>("ShoppingListId")
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingListId", "Index");

                    b.HasIndex("ShopId");

                    b.ToTable("ShoppingListItems");

                    b.HasData(
                        new
                        {
                            ShoppingListId = 1,
                            Index = 0,
                            ShopId = 1,
                            Text = "Carrots"
                        },
                        new
                        {
                            ShoppingListId = 1,
                            Index = 1,
                            Text = "Candy"
                        },
                        new
                        {
                            ShoppingListId = 1,
                            Index = 2,
                            ShopId = 3,
                            Text = "Water"
                        },
                        new
                        {
                            ShoppingListId = 2,
                            Index = 0,
                            Text = "Apples"
                        },
                        new
                        {
                            ShoppingListId = 2,
                            Index = 1,
                            ShopId = 2,
                            Text = "Potatoes"
                        },
                        new
                        {
                            ShoppingListId = 2,
                            Index = 2,
                            ShopId = 2,
                            Text = "Chicken"
                        },
                        new
                        {
                            ShoppingListId = 2,
                            Index = 3,
                            ShopId = 2,
                            Text = "Cheese"
                        });
                });

            modelBuilder.Entity("ShoppingListApp.Domain.ShoppingListItem", b =>
                {
                    b.HasOne("ShoppingListApp.Domain.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId");

                    b.HasOne("ShoppingListApp.Domain.ShoppingList", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
